export enum ModalNames {
  COMPLETE_REGISTRATION = "CompleteRegistration",
  REJECT_REGISTRATION = "RejectRegistration",
  CHANGE_PRODUCER = "ChangeProducer",
  ACCEPT_REGISTRATION = "AcceptRegistration",
  CHANGE_USER = "ChangeUser",
  ADD_TERRITORIALITY = "AddTerritoriality",
  SEARCH_CONFLICTS_FILTERS = "SearchConflictsFilters",
  FIRST_INSTANCE = "FirstInstance",
  SECOND_INSTANCE = "SecondInstance",
  REVISION = "Revision",
  DEFINITION = "Definition",
  CASHFLOW_PAYOUTS_MATCH_REPORT = "CashflowPayoutsMatchReport",
  CASHFLOW_PAYOUTS_IMPORT_PAYOUTS = "CashflowPayoutsImportPayouts",
  CASHFLOW_TRANSFERS = "CashflowTransfers",
  CASHFLOW_IMPORT_PAYMENT = "CashflowImportPayment",
  CASHFLOW_EXPORT_PAYMENTS = "CashflowExportPayments",
  CASHFLOW_IMPORT_REJECTIONS = "CashflowImportRejections",
  CASHFLOW_EXPORT_REJECTIONS = "CashflowExportRejections",
  CASHFLOW_EXPORT_REJECTIONS_REVERSE_PAYMENT = "CashflowExportRejectionsReversePayment",
  GARDEL_AWARDS = "GardelAwards",
  GARDEL_AWARDS_PURGE = "GardelAwardsPurge",
  EXPORT_CHANGES_LIST = "ExportChangesList",
  FINISH_NEW_PHONOGRAM = "FinishNewPhonogram",
}
